# -*- mode: python ; coding: utf-8 -*-
block_cipher = None
a = Analysis(
    ['akserver_gui.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('static/*', 'static'),
        ('html_temp/*', 'html_temp'),
        ('licenses/*', 'licenses'),
        ('system_patch.pkg', '_internal'),
    ],
    hiddenimports=[
        'akserver_analytics',
        'akserver_auth',
        'akserver_config',
        'akserver_gui_connected_devices',
        'akserver_gui_helper_functions',
        'akserver_gui_server_control',
        'akserver_html',
        'akserver_resources',
        'akserver_route_handlers',
        'akserver_route_handlers_api',
        'akserver_route_handlers_auth',
        'akserver_route_handlers_file',
        'akserver_route_handlers_thumbnails',
        'akserver_ssl_util',
        'akserver_trial',
        'akserver_trial_server_token',
        'akserver_trial_status',
        'akserver_trusted_device_manager',
        'firebase_admin',
        'cryptography',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='AkServerApp',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='static/akserver_icon.ico',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    name='AkServerApp'
)