; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "AkServer"
#define MyAppVersion "0.1" ; Change this as you release new versions
#define MyAppPublisher "Your Name or Company"
#define MyAppURL "akserverstorage.blogspot.com" ; Optional
#define MyAppExeName "AkServer_GUI.exe"
#define MyAppServerExeName "AkServer.exe" ; Though not directly run by user
#define MyAppDataRoot "AkServer_Data"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Generate a new GUID: In Inno Setup, Tools > Generate GUID. Paste it here.
AppId={{YOUR-NEW-UNIQUE-GUID-HERE}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableDirPage=no
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=no
OutputBaseFilename=AkServer_Setup_{#MyAppVersion}
Compression=lzma
SolidCompression=yes
SetupIconFile=app_icon.ico
WizardStyle=modern
PrivilegesRequired=admin
[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
; GUI executable and its dependencies (from PyInstaller's dist\AkServer_GUI)
Source: "dist\AkServer_GUI\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Server executable and its dependencies (from PyInstaller's dist\AkServer)
Source: "dist\AkServer\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; Note: AkServer_Startup.bat is already included in dist\AkServer_GUI by PyInstaller
; and will be copied to {app} by the Source line above.

[Dirs]
; Original Dirs in the installation directory ({app}).
; The server now uses ProgramData, so these might be vestigial for the server's core data,
; but can be kept if other parts of your system might use them or for future use.
Name: "{app}\{#MyAppDataRoot}";
Name: "{app}\{#MyAppDataRoot}\Server";
Name: "{app}\{#MyAppDataRoot}\Trial";
Name: "{app}\{#MyAppDataRoot}\Server\logs";

; New Dirs in ProgramData for the server's actual data.
; {commonappdata} maps to C:\ProgramData.
; Permissions: users-full grants standard users full control over these directories.
Name: "{commonappdata}\{#MyAppName}"; Permissions: users-full
Name: "{commonappdata}\{#MyAppName}\AkServer_Data_Server"; Permissions: users-full
Name: "{commonappdata}\{#MyAppName}\AkServer_Data_Server\Server"; Permissions: users-full
Name: "{commonappdata}\{#MyAppName}\AkServer_Data_Server\Server\logs"; Permissions: users-full
Name: "{commonappdata}\{#MyAppName}\AkServer_Data_Server\Trial"; Permissions: users-full

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"
; Create a shortcut to the server startup batch file in the user's Startup folder if the task is selected.
Name: "{userstartup}\{#MyAppName} Server"; Filename: "{app}\AkServer_Startup.bat"; WorkingDir: "{app}"; IconFilename: "{app}\{#MyAppServerExeName}"; Comment: "Starts AkServer automatically"

[Run]
; Run the GUI after installation completes (optional)
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#MyAppName}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; Remove data from the installation directory
Type: filesandordirs; Name: "{app}\{#MyAppDataRoot}"
; Remove the startup shortcut
Type: files; Name: "{userstartup}\{#MyAppName} Server.lnk"
; Optionally, remove data from ProgramData upon uninstallation
Type: filesandordirs; Name: "{commonappdata}\{#MyAppName}\AkServer_Data_Server"
; Optionally, remove the top-level app folder in ProgramData if it's empty after the above
Type: dirifempty; Name: "{commonappdata}\{#MyAppName}"
